services:
  db:
    image: postgres:16-alpine
    container_name: db_devoluciones
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata_devoluciones:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: devoluciones:latest
    container_name: api_devoluciones
    ports: [ "8080:8080" ]
    env_file: .env
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_DATABASE}
      CARGA_DIR: ./carga
    volumes:
      - ./carga:/app/carga
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata_devoluciones:
